jobs:
  make_doc:
    runs-on: main
    steps:
      - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.12.0
      with:
      working-directory: './'
      doxyfile-path: 'Doxygen'
      enable-latex: true
